/*
 * Korean display names for COCO-SSD's 80 object classes and for the
 * dog/cat breed labels MobileNet (ImageNet) can return. Lookups fall back
 * to the original English label when a key is missing, so this table
 * doesn't need to be exhaustive to be safe.
 */
(function (global) {
  const CLASS_LABELS_KO = {
    person: "사람",
    bicycle: "자전거",
    car: "자동차",
    motorcycle: "오토바이",
    airplane: "비행기",
    bus: "버스",
    train: "기차",
    truck: "트럭",
    boat: "보트",
    "traffic light": "신호등",
    "fire hydrant": "소화전",
    "stop sign": "정지 표지판",
    "parking meter": "주차 요금 계산기",
    bench: "벤치",
    bird: "새",
    cat: "고양이",
    dog: "개",
    horse: "말",
    sheep: "양",
    cow: "소",
    elephant: "코끼리",
    bear: "곰",
    zebra: "얼룩말",
    giraffe: "기린",
    backpack: "배낭",
    umbrella: "우산",
    handbag: "핸드백",
    tie: "넥타이",
    suitcase: "여행 가방",
    frisbee: "프리스비",
    skis: "스키",
    snowboard: "스노보드",
    "sports ball": "공",
    kite: "연",
    "baseball bat": "야구 방망이",
    "baseball glove": "야구 글러브",
    skateboard: "스케이트보드",
    surfboard: "서핑보드",
    "tennis racket": "테니스 라켓",
    bottle: "병",
    "wine glass": "와인잔",
    cup: "컵",
    fork: "포크",
    knife: "칼",
    spoon: "숟가락",
    bowl: "그릇",
    banana: "바나나",
    apple: "사과",
    sandwich: "샌드위치",
    orange: "오렌지",
    broccoli: "브로콜리",
    carrot: "당근",
    "hot dog": "핫도그",
    pizza: "피자",
    donut: "도넛",
    cake: "케이크",
    chair: "의자",
    couch: "소파",
    "potted plant": "화분",
    bed: "침대",
    "dining table": "식탁",
    toilet: "변기",
    tv: "TV",
    laptop: "노트북",
    mouse: "마우스",
    remote: "리모컨",
    keyboard: "키보드",
    "cell phone": "휴대폰",
    microwave: "전자레인지",
    oven: "오븐",
    toaster: "토스터",
    sink: "싱크대",
    refrigerator: "냉장고",
    book: "책",
    clock: "시계",
    vase: "꽃병",
    scissors: "가위",
    "teddy bear": "곰인형",
    "hair drier": "헤어드라이어",
    toothbrush: "칫솔",
  };

  // Split into DOG_BREED_LABELS_KO / CAT_BREED_LABELS_KO (rather than one
  // flat table) so breedClassifier.js can use their keys as the
  // authoritative "is this actually a dog/cat breed" set - MobileNet is a
  // general 1000-class ImageNet classifier, so its raw top prediction for a
  // cropped cat/dog can land on an unrelated class (e.g. "ice bear")
  // without that filter.
  const DOG_BREED_LABELS_KO = {
    Chihuahua: "치와와",
    "Japanese spaniel": "재패니즈 친",
    "Maltese dog": "몰티즈",
    Pekinese: "페키니즈",
    "Shih-Tzu": "시츄",
    "Blenheim spaniel": "블레넘 스파니엘",
    papillon: "파피용",
    "toy terrier": "토이 테리어",
    "Rhodesian ridgeback": "로디지안 리지백",
    "Afghan hound": "아프간 하운드",
    basset: "바셋 하운드",
    beagle: "비글",
    bloodhound: "블러드하운드",
    bluetick: "블루틱 쿤하운드",
    "black-and-tan coonhound": "블랙 앤 탄 쿤하운드",
    "Walker hound": "워커 하운드",
    "English foxhound": "잉글리시 폭스하운드",
    redbone: "레드본 쿤하운드",
    borzoi: "보르조이",
    "Irish wolfhound": "아이리시 울프하운드",
    "Italian greyhound": "이탈리안 그레이하운드",
    whippet: "휘핏",
    "Ibizan hound": "이비잔 하운드",
    "Norwegian elkhound": "노르웨이언 엘크하운드",
    otterhound: "오터하운드",
    Saluki: "살루키",
    "Scottish deerhound": "스코티시 디어하운드",
    Weimaraner: "바이마라너",
    "Staffordshire bullterrier": "스태퍼드셔 불테리어",
    "American Staffordshire terrier": "아메리칸 스태퍼드셔 테리어",
    "Bedlington terrier": "베들링턴 테리어",
    "Border terrier": "보더 테리어",
    "Kerry blue terrier": "케리 블루 테리어",
    "Irish terrier": "아이리시 테리어",
    "Norfolk terrier": "노퍽 테리어",
    "Norwich terrier": "노리치 테리어",
    "Yorkshire terrier": "요크셔 테리어",
    "wire-haired fox terrier": "와이어헤어드 폭스테리어",
    "Lakeland terrier": "레이크랜드 테리어",
    "Sealyham terrier": "실리엄 테리어",
    Airedale: "에어데일 테리어",
    cairn: "케언 테리어",
    "Australian terrier": "오스트레일리안 테리어",
    "Dandie Dinmont": "댄디 딘몬트 테리어",
    "Boston bull": "보스턴 테리어",
    "miniature schnauzer": "미니어처 슈나우저",
    "giant schnauzer": "자이언트 슈나우저",
    "standard schnauzer": "스탠다드 슈나우저",
    "Scotch terrier": "스코티시 테리어",
    "Tibetan terrier": "티베탄 테리어",
    "silky terrier": "실키 테리어",
    "soft-coated wheaten terrier": "소프트 코티드 휘튼 테리어",
    "West Highland white terrier": "웨스트 하이랜드 화이트 테리어",
    Lhasa: "라사 압소",
    "flat-coated retriever": "플랫코티드 리트리버",
    "curly-coated retriever": "컬리코티드 리트리버",
    "golden retriever": "골든 리트리버",
    "Labrador retriever": "래브라도 리트리버",
    "Chesapeake Bay retriever": "체서피크 베이 리트리버",
    "German short-haired pointer": "저먼 쇼트헤어드 포인터",
    vizsla: "비즐라",
    "English setter": "잉글리시 세터",
    "Irish setter": "아이리시 세터",
    "Gordon setter": "고든 세터",
    "Brittany spaniel": "브리타니 스파니엘",
    clumber: "클럼버 스파니엘",
    "English springer": "잉글리시 스프링거 스파니엘",
    "Welsh springer spaniel": "웰시 스프링거 스파니엘",
    "cocker spaniel": "코커 스파니엘",
    "Sussex spaniel": "서식스 스파니엘",
    "Irish water spaniel": "아이리시 워터 스파니엘",
    kuvasz: "쿠바스",
    schipperke: "스히퍼르커",
    groenendael: "그로넨달",
    malinois: "말리노이즈",
    briard: "브리아드",
    kelpie: "켈피",
    komondor: "코몬도르",
    "Old English sheepdog": "올드 잉글리시 십독",
    "Shetland sheepdog": "셰틀랜드 십독",
    collie: "콜리",
    "Border collie": "보더 콜리",
    "Bouvier des Flandres": "부비에 데 플랑드르",
    Rottweiler: "로트와일러",
    "German shepherd": "저먼 셰퍼드",
    Doberman: "도베르만",
    "miniature pinscher": "미니어처 핀셔",
    "Greater Swiss Mountain dog": "그레이터 스위스 마운틴 도그",
    "Bernese mountain dog": "버니즈 마운틴 도그",
    Appenzeller: "아펜젤러 마운틴 도그",
    EntleBucher: "앙트르부허 마운틴 도그",
    boxer: "복서",
    "bull mastiff": "불마스티프",
    "Tibetan mastiff": "티베탄 마스티프",
    "French bulldog": "프렌치 불도그",
    "Great Dane": "그레이트 데인",
    "Saint Bernard": "세인트 버나드",
    "Eskimo dog": "에스키모 도그",
    malamute: "알래스칸 맬러뮤트",
    "Siberian husky": "시베리안 허스키",
    affenpinscher: "아펜핀셔",
    basenji: "바센지",
    pug: "퍼그",
    Leonberg: "레온베르거",
    Newfoundland: "뉴펀들랜드",
    "Great Pyrenees": "그레이트 피레니즈",
    Samoyed: "사모예드",
    Pomeranian: "포메라니안",
    chow: "차우차우",
    keeshond: "키스혼트",
    "Brabancon griffon": "브뤼셀 그리펀",
    Pembroke: "펨브록 웰시 코기",
    Cardigan: "카디건 웰시 코기",
    "toy poodle": "토이 푸들",
    "miniature poodle": "미니어처 푸들",
    "standard poodle": "스탠다드 푸들",
    "Mexican hairless": "멕시칸 헤어리스 도그",
    dingo: "딩고",
    dhole: "승냥이",
    "African hunting dog": "아프리카들개",
  };

  const CAT_BREED_LABELS_KO = {
    tabby: "태비 고양이",
    "tiger cat": "타이거 캣",
    "Persian cat": "페르시안 고양이",
    "Siamese cat": "샴 고양이",
    "Egyptian cat": "이집션 마우",
  };

  // Labels the custom Oxford-IIIT Pet model (models/custom-breeds/) uses -
  // a different naming convention than ImageNet's, and that backend already
  // only ever outputs from this fixed set, so it doesn't need the
  // dog/cat-breed validity filtering DOG_BREED_LABELS_KO/CAT_BREED_LABELS_KO
  // exist for.
  const CUSTOM_MODEL_LABELS_KO = {
    Persian: "페르시안 고양이",
    Siamese: "샴 고양이",
    Bengal: "벵골 고양이",
    yorkshire_terrier: "요크셔 테리어",
  };

  const BREED_LABELS_KO = { ...DOG_BREED_LABELS_KO, ...CAT_BREED_LABELS_KO, ...CUSTOM_MODEL_LABELS_KO };

  global.CLASS_LABELS_KO = CLASS_LABELS_KO;
  global.BREED_LABELS_KO = BREED_LABELS_KO;
  global.DOG_BREED_LABELS_KO = DOG_BREED_LABELS_KO;
  global.CAT_BREED_LABELS_KO = CAT_BREED_LABELS_KO;
  global.classLabelKo = function (en) {
    return CLASS_LABELS_KO[en] || en;
  };
  global.breedLabelKo = function (en) {
    return BREED_LABELS_KO[en] || en;
  };
})(window);
